//console.log('Hello from typescript')
// types
var myString;
var myNumber;
var myBoolean;
var myStrArr;
var myNumArr;
var myBooArr;
var strNumBooTuple;
var anything;
var myUndif = undefined;
var myNull = null;
myString = "hello from mystring";
myNumber = 1;
myBoolean = false;
myStrArr = ["str", "no numbers", "no booleans"];
myNumArr = [2, 3, 4];
myBooArr = [true, false, false];
strNumBooTuple = ["str", 56, true];
anything = ['stirng', 2];
//console.log(myString);
//console.log(myNumber);
//console.log(myBoolean);
//console.log(myStrArr);
//console.log(myNumArr);
//console.log(myBooArr);
//console.log(strNumBooTuple);
//console.log(anything);
//console.log(myUndif);
//console.log(myNull);
